services:
  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: Dockerfile
      target: base,
    volumes:
      - ../backend/src:/usr/app/src
    expose:
      - "3001:3001"
    command: npm run dev
    depends_on:
      - db
    networks:
      - public
      - private
    env_file:
      - ../config/environment-variables/backend.dev.env

  db:
    container_name: db
    image: mongo:4.4
    ports:
      - "27017:27017"
    networks:
      - private
    volumes:
      - db-data:/data/db

networks:
  public:
    external: true
    driver: bridge
  private:
    internal: true
    driver: bridge
    
volumes:
  db-data: {}