services:
  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: Dockerfile
      target: base,
    volumes:
      - ../backend/src:/usr/app/src
    expose:
      - "3001:3001"
    command: npm run dev
    depends_on:
      - db
    env_file:
      - ../config/environment-variables/backend.dev.env

  db:
    container_name: db
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - ../config/environment-variables/db.dev.env
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
