services:
  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: Dockerfile
      target: base
    ports:
      - "3001:3001" # Expose HTTPS on port 3001
    volumes:
      - ../backend/src:/usr/src/app/src
      - ../schemas:/usr/src/app/schemas
      - ../backend/nodemon.json:/usr/src/app/nodemon.json
    command: npm run dev
    depends_on:
      - db
    env_file:
      - ../config/environment-variables/backend.dev.env
    networks:
      - public
      - private

  db:
    container_name: db
    image: mongo:4.4
    ports:
      - "27017:27017"
    command:
      [
        "mongod",
        "--keyFile",
        "/data/keyfile.pem",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    networks:
      - private
    volumes:
      - mongo1_data:/data/db
      - mongo1_config:/data/configdb

networks:
  public:
    external: true
    driver: bridge
  private:
    internal: true
    driver: bridge

volumes:
  mongo1_data: {}
  mongo1_config: {}
