name: Cafe Vesuvius

services:
  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: Dockerfile
      target: base
    expose:
      - "3001:3001"
    ports:
      - "3001:3001"
    command: npm run dev
    depends_on:
      - db
    env_file:
      - ../config/environment-variables/backend.dev.env
    volumes:
     - ../backend/src:/usr/src/app/src
     - ../schemas:/usr/src/app/schemas
     - ../backend/nodemon.json:/usr/src/app/nodemon.json

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "27017:27017"
    command:
      [
        "mongod",
        "--keyFile",
        "/data/keyfile.pem",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ../config/environment-variables/db.dev.env
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

volumes:
  mongo1_data: {}
  mongo1_config: {}