services:
  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: Dockerfile
      target: base
    expose:
      - "3001:3001"
    ports:
      - "3001:3001"
    command: npm run dev
    develop: 
       watch:
        - action: sync
          path: ../backend/src
          target: /usr/app/src

        - action: rebuild
          path: ../backend/package.json
          target: /usr/app
    depends_on:
      - db
    env_file:
      - ../config/environment-variables/backend.dev.env

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    ports:
      - "27017:27017"
    command: >
      bash -c "
        mongod --keyFile /data/keyfile.pem --replSet rs0 --bind_ip_all --port 27017 &
        until mongosh --host localhost --port 27017 --eval 'print(\"Waiting for MongoDB to be ready...\")'; do
          sleep 5;
        done;
        ./docker-entrypoint-initdb.d/init.sh
      "
    env_file:
      - ../config/environment-variables/db.dev.env
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

volumes:
  mongo1_data: {}
  mongo1_config: {}