name: Cafe Vesuvius

services:
  backend:
    container_name: backend
    build:
      context: ../backend/
      dockerfile: Dockerfile
      target: base
    expose:
      - "3001"
    ports:
      - "3001:3001"
    command: npm run dev
    depends_on:
      - db
    env_file:
      - ../config/environment-variables/.env.backend.dev
    volumes:
      - ../backend/src:/usr/src/app/src
      - ../schemas:/usr/src/app/schemas
      - ../backend/nodemon.json:/usr/src/app/nodemon.json
    networks:
      - internal

  db:
    container_name: db
    build:
      context: .
      dockerfile: db.Dockerfile
    expose:
      - "27017"
    ports:
      - "27017:27017"
    command:
      [
        "mongod",
        "--keyFile",
        "/data/keyfile.pem",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--port",
        "27017",
      ]
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ../config/environment-variables/.env.db.dev
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"
    networks:
      - public
      - internal

  reverse-proxy:
    container_name: reverse-proxy
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    ports:
      - 443:443
      - 80:80
    depends_on:
      - backend
    volumes:
      - "../config/nginx.conf:/etc/nginx/nginx.conf"
    networks:
      - internal

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command:
      - "http"
      - "http://reverse-proxy:80"
      - "--url=${NGROK_URL}"
    ports:
      - 4040:4040
    env_file:
      - ../config/environment-variables/.env.grok.dev
    networks:
      - public
      - internal

networks:
  public:
    driver: bridge
  internal:
    name: internal
    internal: true

volumes:
  mongo1_data: {}
  mongo1_config: {}
